# Generated by Django 3.1.2 on 2022-08-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messaging',
            old_name='receiver',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='messaging',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
