SET search_path TO sunset_vacation,public;
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Hair Dryer','amenity','Bathroom');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Shampoo','amenity','Bathroom');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Hangers','amenity','Bedroom & Laundry');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Washers','amenity','Bedroom & Laundry');

insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('TV','amenity','Entertainment');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Air Conditioning','amenity','Heating & Cooling');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Carbon monoxide alarm','safety','Home safety');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Smoke alarm','safety','Home safety');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Fire extinguisher','safety','Home safety');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('First aid kit','safety','Home safety');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Wifi','amenity','Internet');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Pool','guestFav','Parking & Facilities');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Breakfast','amenity','Services');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Long term stays allowed','amenity','Services');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Kitchen','amenity','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Gym','guestFav','Parking & Facilities');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Heating','amenity','Heating & Cooling');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Refrigerator','amenity','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Microwave','amenity','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Dishes','amenity','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Stove','amenity','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Oven','amenity','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Coffee maker','guestFav','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Toaster','guestFav','Kitchen and dining');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Bay view','guestFav','Scenic views');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Sea view','guestFav','Scenic views');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Balcony','guestFav','Outdoor');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Backyard','guestFav','Outdoor');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Boat slip','guestFav','Outdoor');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Free parking on premises','amenity','Parking & Facilities');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Hot water','amenity','Bathroom');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Lock on bedroom door','safety','Home safety');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('Free street parking','amenity','Parking & Facilities');
insert into "Hosting_facility" (facility_name,catagory,subcatagory) values('What's new','guestFav','Others');
select * from "Hosting_facility";