from django.urls import path
from . import views


urlpatterns = [
    #path('<int:user_id>/', views.getProperties),
    path('addCategory/', views.addCategory),
    path('addFacility/', views.addFacility),
    path('facilityCategories/', views.getFacilityCategories),
    path('facilitySubcategories/', views.getFacilitySubcategories),
    path('pendingProperties/', views.getPendingProperties),
    path('approve/<int:propertyId>',views.approveProperty),
    path('reject/<int:propertyId>',views.rejectProperty),
    path('notification/<int:notification_id>', views.getNotificationId),
    path('notification/', views.getNotification),
    path('deleteNotification/<int:notification_id>', views.deleteNotification),
    path('propertylist/', views.getProperties),
    path('facilitylist/',views.getFacilities),
    path('insertOffer/',views.insertOffer),
    path('updateProperty/<int:property_id>',views.updatePropertyDetails),
    path('deleteProperty/<int:property_id>',views.deleteProperty),
    path('addNewFacility/<int:property_id>',views.addNewFacility),
    path('deleteFacility/<int:fac_id>',views.deleteFacility),
    path('photos/<int:photo_id>', views.deletePropertyPhoto),
    path('getPropertyPhoto/<int:property_id>', views.getPropertyPhoto, name="getPropertyPhoto"),
    path('deleteFaq/<int:faq_id>',views.deleteFaq),
    path('getProperty/<int:property_id>',views.getProperty),
    path('getFaqs/<int:property_id>',views.getFaqs),
    path('getOfferList/',views.getOfferList),
    path('insertFaq/<int:property_id>',views.insertFaq),
    path('getPropertyFacilities/<int:property_id>',views.getPropertyFacilities),
    path('updatePropertyFacility/<int:fac_id>',views.updatePropertyFacility),
    path('getPropertyFacilityDetails/<int:fid>',views.getPropertyFacilityDetails),
    path('getAddFacilityList/<int:property_id>',views.getAddFacilityList),
    path('getallcategory/', views.getCategoryList, name="getcategorylist"),
    path('getfacilities/',views.getFacilityList, name="getfacilitylist" ),
    path('property/publish/', views.publishProperty, name="publishProperty"),
    path('photouploadhelper/', views.photoUpload, name="photouploadhelper"),
    path('updatephotouploadhelper/', views.updatePhotoUploadHelper, name="updatephotouploadhelper"),
    path('getallpropertiesforhomepage/', views.getAllPropertiesForHomePage, name='getallproperties'),
    path('addreview/', views.addReview, name="addReview"),
    # path('getsafetyitems/', views.getSafetyItemList, name="getsafetyitemlist"),
    # path('propertylist/', views.getPropertyDetails),
    path('recommandations/', views.Recommendations),
    path('getSearchResult/<str:searchword>/',views.getSearchResult),
    path('getCatagoryForSearch/',views.getCatagoryForSearch),
    path('getPropertyCatagory/',views.getPropertyCatagory),
    path('getUserStaticSearch/',views.getUserStaticSearch),
    path('getGuestList/',views.getGuestList),
    path('insertGiftcard/',views.insertGiftcard),
    path('deleteGiftcard/<int:giftcard_id>',views.deleteGiftcard),
    path('getGiftcardList/',views.getGiftcardList),
    path('addrating/', views.addRating),
    path('getlocationsInCountry/<str:country>/',views.getlocationsInCountry),
    path('getCountryList/',views.getCountryList),
    path('getHomepagesearchResult/',views.getHomepagesearchResult),
]
