# Generated by Django 3.1.2 on 2022-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('propertyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('catagory', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('perNightCost', models.FloatField(default=None)),
                ('checkInTime', models.DateTimeField(default=None)),
                ('checkOutTime', models.DateTimeField(default=None)),
                ('maxDaysRefund', models.IntegerField(default=None)),
                ('noOfGuests', models.IntegerField(default=None)),
                ('noOfBeds', models.IntegerField(default=None)),
                ('noOfBathrooms', models.IntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=500, null=True)),
                ('latitude', models.CharField(default=None, max_length=500, null=True)),
                ('longitude', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
