# Generated by Django 3.1.2 on 2022-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='checkInTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='checkOutTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='maxDaysRefund',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='noOfBathrooms',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='noOfBeds',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='noOfGuests',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='perNightCost',
            field=models.FloatField(default=None, null=True),
        ),
    ]
