# Generated by Django 3.1.2 on 2022-07-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0001_initial'),
    ]

    operations = [
    ]
