# Generated by Django 4.0.1 on 2022-07-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='conciseType',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='entirePrivateOrShared',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
