# Generated by Django 3.1.2 on 2022-07-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(default=None, max_length=500)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hosting.property')),
            ],
        ),
    ]
