# Generated by Django 4.0.5 on 2022-07-17 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='checkInTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='checkOutTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
