# Generated by Django 4.0.5 on 2022-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0002_propertyphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='noOfBedrooms',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='propertyphotos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
