# Generated by Django 4.0.1 on 2022-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0002_property_concisetype_property_entireprivateorshared'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='noOfBedrooms',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
