# Generated by Django 4.0.5 on 2022-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0003_property_noofbedrooms_alter_propertyphotos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphotos',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
    ]
