# Generated by Django 3.1.2 on 2022-07-31 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hosting', '0003_auto_20220717_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hosting.offer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
