# Generated by Django 3.1.2 on 2022-07-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0004_useroffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOffer',
        ),
    ]
