# Generated by Django 3.1.2 on 2022-07-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0005_propertyphotouploadhelper_and_more'),
        ('Hosting', '0003_property_noofbedrooms'),
    ]

    operations = [
    ]
