# Generated by Django 3.1.2 on 2022-08-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0002_auto_20220824_1955'),
        ('Hosting', '0005_alter_messaging_time'),
    ]

    operations = [
    ]
