# Generated by Django 4.0.1 on 2022-08-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0005_alter_messaging_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='marked',
        ),
        migrations.AddField(
            model_name='messaging',
            name='rmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messaging',
            name='smarked',
            field=models.BooleanField(default=False),
        ),
    ]
