# Generated by Django 4.0.1 on 2022-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0006_alter_notification_id_alter_propertyfacilities_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySubcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
