# Generated by Django 4.0.5 on 2022-08-13 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0006_alter_notification_id_alter_propertyfacilities_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaging',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
