# Generated by Django 4.0.1 on 2022-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0006_remove_messaging_marked_messaging_rmarked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='rmarked',
        ),
        migrations.RemoveField(
            model_name='messaging',
            name='smarked',
        ),
        migrations.AddField(
            model_name='messaging',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
