# Generated by Django 3.1.2 on 2022-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0007_auto_20220715_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='subcatagory',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
