# Generated by Django 4.0.1 on 2022-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0008_notification_title_alter_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
