# Generated by Django 3.1.2 on 2022-08-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAForum', '0002_questionproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag_ids',
        ),
    ]
