# Generated by Django 3.1.2 on 2022-08-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0002_auto_20220824_1955'),
        ('QAForum', '0003_auto_20220824_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionproperty',
            name='propertyID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hosting.property'),
        ),
        migrations.AlterField(
            model_name='questionproperty',
            name='questionID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QAForum.question'),
        ),
    ]
