# Generated by Django 3.1.2 on 2022-08-25 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosting', '0002_auto_20220824_1955'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QAForum', '0004_auto_20220824_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerReact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionReact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='answer',
            name='react',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='react',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestionreact',
            name='questionID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QAForum.question'),
        ),
        migrations.AddField(
            model_name='userquestionreact',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswerreact',
            name='answerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QAForum.answer'),
        ),
        migrations.AddField(
            model_name='useranswerreact',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerproperty',
            name='answerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QAForum.answer'),
        ),
        migrations.AddField(
            model_name='answerproperty',
            name='propertyID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hosting.property'),
        ),
    ]
