# Generated by Django 3.1.2 on 2022-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAForum', '0005_auto_20220825_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='react',
        ),
        migrations.RemoveField(
            model_name='question',
            name='react',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='dislikecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
