# Generated by Django 3.1.2 on 2022-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
