# Generated by Django 4.0.5 on 2022-08-11 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hosting', '0003_alter_notification_id_alter_propertyfacilities_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=None, null=True)),
                ('paytime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('method', models.CharField(default=None, max_length=100, null=True)),
                ('discount', models.FloatField(default=0, null=True)),
                ('receipt_url', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('noOfGuests', models.IntegerField(default=None, null=True)),
                ('arrived', models.BooleanField(default=False)),
                ('payment_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Booking.payment')),
                ('property_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hosting.property')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
