# Generated by Django 4.0.5 on 2022-08-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
