# Generated by Django 4.0.5 on 2022-08-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_payment_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
